service: mail-parser-service

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-northeast-1
  stage: dev

plugins:
  - serverless-offline

functions:
  parse:
    handler: handler.parse
    events:
      - http:
          path: parse
          method: post
          integration: lambda
          request:
            template:
              application/json: >
                {
                  "json": $input.json('$')
                }

